const { PrismaClient } = require('@prisma/client');
const fs = require('fs');
const path = require('path');

const BACKUP_DIR = path.join(__dirname, '..', 'backups', new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19));

async function backup() {
  const prisma = new PrismaClient();
  
  try {
    fs.mkdirSync(BACKUP_DIR, { recursive: true });
    
    const tables = [
      { name: 'User', model: prisma.user },
      { name: 'Work', model: prisma.work },
      { name: 'WorkView', model: prisma.workView },
      { name: 'Review', model: prisma.review },
      { name: 'SiteConfig', model: prisma.siteConfig },
      { name: 'Contact', model: prisma.contact },
      { name: 'ForumCategory', model: prisma.forumCategory },
      { name: 'ForumPost', model: prisma.forumPost },
      { name: 'ForumTag', model: prisma.forumTag },
      { name: 'ForumPostTag', model: prisma.forumPostTag },
      { name: 'ForumComment', model: prisma.forumComment },
      { name: 'ForumPostLike', model: prisma.forumPostLike },
      { name: 'PointsRecord', model: prisma.pointsRecord },
      { name: 'SiteAnalytics', model: prisma.siteAnalytics },
      { name: 'Canvas', model: prisma.canvas },
      { name: 'Pixel', model: prisma.pixel },
      { name: 'CanvasExpansion', model: prisma.canvasExpansion },
      { name: 'CanvasPixelCount', model: prisma.canvasPixelCount },
      { name: 'Transaction', model: prisma.transaction },
      { name: 'MarketplaceListing', model: prisma.marketplaceListing },
      { name: 'Referral', model: prisma.referral },
      { name: 'RateLimitEntry', model: prisma.rateLimitEntry },
      { name: 'VideoReview', model: prisma.videoReview },
      { name: 'ReviewComment', model: prisma.reviewComment },
    ];

    let totalRecords = 0;
    const summary = {};

    for (const { name, model } of tables) {
      try {
        const records = await model.findMany();
        totalRecords += records.length;
        summary[name] = records.length;
        
        const filePath = path.join(BACKUP_DIR, `${name}.json`);
        fs.writeFileSync(filePath, JSON.stringify(records, null, 2));
        console.log(`  ✅ ${name}: ${records.length} rows`);
      } catch (e) {
        console.log(`  ⚠️ ${name}: ERROR - ${e.message}`);
        summary[name] = `ERROR: ${e.message}`;
      }
    }

    // Write summary
    summary.totalRecords = totalRecords;
    summary.backupTime = new Date().toISOString();
    summary.tables = tables.length;
    fs.writeFileSync(
      path.join(BACKUP_DIR, '_summary.json'),
      JSON.stringify(summary, null, 2)
    );

    console.log(`\n📦 Backup complete: ${BACKUP_DIR}`);
    console.log(`📊 Total records: ${totalRecords} across ${tables.length} tables`);
    
    // Also create a SQL dump using raw queries
    console.log(`\n📝 Creating SQL dump...`);
    try {
      // Get all table names
      const tableResults = await prisma.$queryRaw`SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = 'public'`;
      let sqlDump = `-- Database backup: ${new Date().toISOString()}\n-- Generated by alights-website backup script\n\n`;
      
      for (const row of tableResults) {
        const tableName = row.tablename;
        // Skip Prisma internal tables
        if (tableName.startsWith('_prisma') || tableName.startsWith('_')) continue;
        
        const columnInfo = await prisma.$queryRawUnsafe(`
          SELECT column_name, data_type FROM information_schema.columns 
          WHERE table_schema = 'public' AND table_name = '${tableName}' ORDER BY ordinal_position
        `);
        const columns = columnInfo.map(c => `"${c.column_name}"`).join(', ');
        
        const rows = await prisma.$queryRawUnsafe(`SELECT * FROM "${tableName}"`);
        
        sqlDump += `-- Table: ${tableName} (${rows.length} rows)\n`;
        
        for (const row of rows) {
          const values = columnInfo.map(c => {
            const val = row[c.column_name];
            if (val === null) return 'NULL';
            if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
            if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
            if (val instanceof Date) return `'${val.toISOString()}'`;
            if (Array.isArray(val)) return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
            if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
            return String(val);
          }).join(', ');
          
          sqlDump += `INSERT INTO "${tableName}" (${columns}) VALUES (${values});\n`;
        }
        sqlDump += '\n';
      }
      
      fs.writeFileSync(path.join(BACKUP_DIR, 'full-dump.sql'), sqlDump);
      console.log(`  ✅ SQL dump saved: full-dump.sql`);
    } catch (e) {
      console.log(`  ⚠️ SQL dump failed: ${e.message}`);
    }

    return summary;
  } catch (e) {
    console.error('❌ Backup failed:', e.message);
    throw e;
  } finally {
    await prisma.$disconnect();
  }
}

backup()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
