"""
Generate Baidu search URLs (GBK encoded) for all 100 paintings.
Output: JSON file with {id, keyword, url}
"""
import os, json

PAINTINGS = [
    ("american-gothic","美国哥特式"),
    ("composition-vii","构成第七号"),
    ("girl-with-pearl-earring","戴珍珠耳环的少女"),
    ("great-wave","神奈川冲浪里"),
    ("guernica","格尔尼卡"),
    ("las-meninas","宫娥"),
    ("mona-lisa","蒙娜丽莎"),
    ("red-balloon","红气球"),
    ("starry-night","星月夜"),
    ("sunflowers","向日葵"),
    ("the-birth-of-venus","维纳斯的诞生"),
    ("the-garden-of-earthly-delights","人间乐园"),
    ("the-kiss","吻"),
    ("the-last-supper","最后的晚餐"),
    ("the-night-watch","夜巡"),
    ("the-persistence-of-memory","记忆的永恒"),
    ("the-scream","呐喊"),
    ("the-sistine-chapel-ceiling","西斯廷天顶画"),
    ("the-thinker","思想者"),
    ("water-lilies","睡莲"),
    ("iris","鸢尾花"),
    ("liberty","自由引导人民"),
    ("night-cafe","夜间咖啡馆"),
    ("cafe-terrace","夜间的露天咖啡座"),
    ("sleeping-gypsy","沉睡的吉普赛人"),
    ("olympia","奥林匹亚"),
    ("saturday-afternoon","大碗岛的星期天下午"),
    ("saturn-devouring","农神食子"),
    ("third-of-may","1808年5月3日"),
    ("school-of-athens","雅典学院"),
    ("the-creation-of-adam","创造亚当"),
    ("the-calling-of-saint-matthew","圣马太蒙召"),
    ("the-milkmaid","倒牛奶的女仆"),
    ("view-of-delft","代尔夫特风景"),
    ("the-arnolfini-portrait","阿尔诺芬尼夫妇像"),
    ("the-ghent-altarpiece","根特祭坛画"),
    ("the-ambassadors","大使们"),
    ("hunters-in-the-snow","雪中猎人"),
    ("the-tower-of-babel","巴别塔"),
    ("the-harvesters","收割者"),
    ("the-fall-of-icarus","伊卡洛斯的坠落"),
    ("self-portrait-van-gogh","梵高自画像"),
    ("almond-blossoms","杏花"),
    ("wheatfield-with-crows","麦田上的乌鸦"),
    ("bedroom-in-arles","阿尔勒的卧室"),
    ("the-potato-eaters","吃土豆的人"),
    ("portrait-of-dr-gachet","加歇医生像"),
    ("van-gogh-chair","梵高的椅子"),
    ("impression-sunrise","日出印象"),
    ("woman-with-parasol","撑阳伞的女人"),
    ("japanese-bridge","日本桥"),
    ("haystacks","干草堆"),
    ("rouen-cathedral","鲁昂大教堂"),
    ("dance-at-le-moulin","煎饼磨坊的舞会"),
    ("luncheon-of-boating-party","船上的午宴"),
    ("the-swing","秋千"),
    ("the-large-bathers","大浴女"),
    ("whistlers-mother","惠斯勒的母亲"),
    ("the-fighting-temeraire","被拖去解体的战舰"),
    ("rain-steam-speed","雨蒸汽速度"),
    ("the-hay-wain","干草车"),
    ("dedham-vale","德汉峡谷"),
    ("the-blue-boy","蓝衣少年"),
    ("mr-and-mrs-andrews","安德鲁斯夫妇"),
    ("the-sistine-madonna","西斯廷圣母"),
    ("the-transfiguration","基督变容"),
    ("judith-holofernes","朱迪斯斩杀赫罗弗尼斯"),
    ("the-entombment","基督下葬"),
    ("the-death-of-marat","马拉之死"),
    ("napoleon-crossing-alps","拿破仑穿越阿尔卑斯山"),
    ("oath-of-horatii","贺拉斯兄弟之誓"),
    ("the-return-of-prodigal-son","浪子回头"),
    ("the-jewish-bride","犹太新娘"),
    ("anatomy-lesson","杜尔普医生的解剖课"),
    ("belshazzar-feast","伯沙撒的盛宴"),
    ("woman-holding-balance","持天平的女人"),
    ("the-geographer","地理学家"),
    ("the-astronomer","天文学家"),
    ("girl-reading-letter","读信的蓝衣女子"),
    ("the-art-of-painting","绘画艺术"),
    ("the-lacemaker","织花边的女子"),
    ("the-three-graces","美惠三女神"),
    ("the-garden-of-love","爱之园"),
    ("the-rape-of-europa","劫夺欧罗巴"),
    ("venus-of-urbino","乌尔比诺的维纳斯"),
    ("bacchus-and-ariadne","巴库斯与阿里阿德涅"),
    ("assumption-of-virgin","圣母升天"),
    ("the-surrender-breda","布雷达的投降"),
    ("still-life-apples","苹果与橘子"),
    ("the-card-players","玩纸牌的人"),
    ("mount-sainte-victoire","圣维克多山"),
    ("dance-matisse","舞蹈"),
    ("the-red-studio","红色画室"),
    ("woman-with-hat","戴帽子的女人"),
    ("demoiselles-davignon","亚威农少女"),
    ("the-old-guitarist","老吉他手"),
    ("three-musicians","三个音乐家"),
    ("weeping-woman","哭泣的女人"),
    ("the-dream","梦"),
    ("nighthawks","夜鹰"),
    ("christinas-world","克里斯蒂娜的世界"),
    ("campbells-soup","金宝汤罐头"),
    ("marilyn-diptych","玛丽莲双联画"),
    ("yellow-red-blue","黄红蓝"),
    ("broadway-boogie","百老汇爵士乐"),
    ("composition-red-blue","红黄蓝构成"),
    ("convergence","聚合"),
]

def gbk_url(keyword):
    encoded = keyword.encode('gbk', errors='replace')
    return ''.join(f'%{b:02X}' for b in encoded)

entries = []
for pid, kw in PAINTINGS:
    gbk = gbk_url(kw)
    url = f"https://image.baidu.com/search/acjson?tn=resultjson_com&word={gbk}&pn=0&rn=1"
    entries.append({"id": pid, "keyword": kw, "gbk": gbk, "url": url})

with open("/tmp/baidu_urls.json", "w") as f:
    json.dump(entries, f, ensure_ascii=False, indent=2)

print(f"Generated {len(entries)} Baidu search URLs")
print(f"Saved to /tmp/baidu_urls.json")
